### ISSUE TITLE
Following instructions for Next.JS boilerplate and running into some errors.

### ISSUE THREAD

**Issue by LoganSimonsen** [cosmicjs/nextjs-website-boilerplate#3]
I've ran into a few errors when trying to run npm install and then npm run dev. Errors are below:

`Logan@LoganHPlaptop MINGW64 ~/DevMountain/github_command/CosmicJS/nextjs-website-boilerplate (master)
$ npm install
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 23.374s

Logan@LoganHPlaptop MINGW64 ~/DevMountain/github_command/CosmicJS/nextjs-website-boilerplate (master)
$ npm run dev

> medical-professional-next@1.0.0 dev C:\Users\Logan\DevMountain\github_command\CosmicJS\nextjs-website-boilerplate
> babel-node server.js --presets es2015 stage-2

_'babel-node' is not recognized as an internal or external command_,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medical-professional-next@1.0.0 dev: `babel-node server.js --presets es2015 stage-2`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medical-professional-next@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Logan\AppData\Roaming\npm-cache\_logs\2018-05-12T18_03_09_522Z-debug.log
`

So do I just need to install some other dependencies?

**Comment by LoganSimonsen** [comment]
I resolved my issue by updating react and react-dom to version 16.3.2

**Comment by tonyspiro** [comment]
Can't reproduce this issue.
